name: FortiDevSec Scanner CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run FortiDevSec SAST
        env:
          FORTIDEVSEC_TOKEN: ${{ secrets.FORTIDEVSEC_TOKEN }}
        run: |
          docker pull registry.fortidevsec.forticloud.com/fdevsec_sast:latest
          docker run --rm \
            -v "${{ github.workspace }}":/scan \
            -e FORTIDEVSEC_TOKEN=$FORTIDEVSEC_TOKEN \
            -e FORTIDEVSEC_CI=true \
            -e FORTIDEVSEC_REPO_NAME=${{ github.repository }} \
            -e FORTIDEVSEC_BRANCH=${{ github.ref_name }} \
            -e FORTIDEVSEC_COMMIT=${{ github.sha }} \
            registry.fortidevsec.forticloud.com/fdevsec_sast:latest

