name: FortiDevSec Scanner CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: FortiDevSec Scan
        env:
          FORTIDEVSEC_TOKEN: ${{ secrets.FORTIDEVSEC_TOKEN }}
        run: |
          env | grep -E "GITHUB_ACTIONS|GITHUB_RUN_NUMBER|GITHUB_REF_NAME|GITHUB_SHA|GITHUB_REPOSITORY" > /tmp/env
          echo "FORTIDEVSEC_TOKEN=$FORTIDEVSEC_TOKEN" >> /tmp/env
          docker run --pull always --rm \
            --env-file /tmp/env \
            --mount type=bind,source=$PWD,target=/scan \
            registry.fortidevsec.forticloud.com/fdevsec_sast:latest

